# Generated by Django 5.1.6 on 2025-02-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
    ]
