# Generated by Django 5.1.6 on 2025-02-28 09:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
