# Generated by Django 5.1.6 on 2025-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htmx", "0006_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("likes", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
