# Generated by Django 5.1.6 on 2025-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fetch", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
